### ISSUE TITLE
CSRF Warning! State not equal in request and response.

### ISSUE THREAD

**Issue by HomeLandGIT** [zigam/tesla-solar-download#4]
Hi When running this script i get the following error.

Traceback (most recent call last):
  File "/home/homeland/tesla-solar-download/./tesla_solar_download.py", line 362, in <module>
    main()
  File "/home/homeland/tesla-solar-download/./tesla_solar_download.py", line 332, in main
    tesla.fetch_token(authorization_response=input('URL after authentication: '))
  File "/venv/lib/python3.10/site-packages/teslapy/__init__.py", line 230, in fetch_token
    super(Tesla, self).fetch_token(token_url, **kwargs)
  File "/venv/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_uri_response(
  File "/venv/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 220, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "/venv/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 278, in parse_authorization_code_response
    raise MismatchingStateError()
oauthlib.oauth2.rfc6749.errors.MismatchingStateError: (mismatching_state) CSRF Warning! State not equal in request and response.

**Comment by zigam** [comment]
This would suggest the url of the "Page Not Found" page shown after login was not copied correctly.  After you log in with Tesla, you'll need to copy the entire url and paste in the console.  The url will look like this:

```
https://auth.tesla.com/void/callback?code=NA_REDACTED&state=REDACTED&issuer=https%3A%2F%2Fauth.tesla.com%2Foauth2%2Fv3
```

If the `state` parameter is missing or doesn't match the one from the initial login url, you'll get the CSRF error.
